FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_PREFER_BINARY=1 \
    CMAKE_BUILD_PARALLEL_LEVEL=8

# System deps (libgl1 replaces libgl1-mesa-glx on Ubuntu 24.04)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.12 python3.12-venv python3.12-dev python3-pip \
    build-essential gcc g++ ninja-build \
    git git-lfs aria2 ffmpeg wget curl ca-certificates \
    libgl1 libglib2.0-0 libopenblas-dev liblapack-dev \
    && ln -sf /usr/bin/python3.12 /usr/bin/python3 \
    && ln -sf /usr/bin/python3.12 /usr/bin/python \
    && python3.12 -m venv /opt/venv \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/venv/bin:$PATH"

# Copy the lockfile that pins every git SHA (ComfyUI core + each custom node).
# Generated by scripts/freeze.py from the local ComfyUI tree. All clones below
# read SHAs from this file — any cache-busting tag bump is reflected in lockfile
# changes, so docker layer caching invalidates only when SHAs actually move.
COPY nodes.lock /nodes.lock

# ComfyUI + all deps (includes torch, safetensors, transformers, etc.)
# Pinned to the SHA in nodes.lock so every build of v<N> resolves to the same tree.
RUN pip install --upgrade pip setuptools wheel packaging && \
    COMFY_SHA=$(awk '$1=="https://github.com/comfyanonymous/ComfyUI.git"{print $2}' /nodes.lock) && \
    if [ -z "$COMFY_SHA" ]; then echo "FATAL: ComfyUI SHA missing from nodes.lock" >&2; exit 1; fi && \
    git clone https://github.com/comfyanonymous/ComfyUI.git /ComfyUI && \
    git -C /ComfyUI checkout "$COMFY_SHA" && \
    pip install -r /ComfyUI/requirements.txt

# Freeze torch versions to prevent custom node deps from upgrading/downgrading
RUN pip freeze | grep -E "^(torch|torchvision|torchaudio|torchsde)==" > /torch-constraint.txt

# SageAttention (pre-built wheel)
COPY sageattention-2.2.0-cp312-cp312-linux_x86_64.whl /tmp/
RUN pip install /tmp/sageattention-2.2.0-cp312-cp312-linux_x86_64.whl && \
    rm /tmp/sageattention-2.2.0-cp312-cp312-linux_x86_64.whl

# RunPod SDK + runtime deps
RUN pip install runpod boto3 requests websocket-client

# Clone and install all custom nodes — pinned to SHAs in /nodes.lock.
# Each line is '<url> <sha>'. We skip the ComfyUI core entry (already cloned
# above) and clone each node, then `git checkout <sha>` to lock the tree.
# Bumping a node SHA is a one-line edit in nodes.lock (regenerate via
# scripts/freeze.py from the local ComfyUI tree).
RUN set -e; \
    while read -r url sha; do \
      case "$url" in ''|'#'*) continue ;; esac; \
      [ "$url" = "https://github.com/comfyanonymous/ComfyUI.git" ] && continue; \
      cd /ComfyUI/custom_nodes; \
      repo_dir=$(basename "$url" .git); \
      echo "=== Installing $repo_dir @ ${sha:0:8} ==="; \
      git clone "$url" "$repo_dir"; \
      git -C "$repo_dir" checkout "$sha"; \
      if [ -f "/ComfyUI/custom_nodes/$repo_dir/requirements.txt" ]; then \
        pip install -r "/ComfyUI/custom_nodes/$repo_dir/requirements.txt" \
          --constraint /torch-constraint.txt || \
          echo "WARNING: some deps failed for $repo_dir (continuing)"; \
      fi; \
      if [ -f "/ComfyUI/custom_nodes/$repo_dir/install.py" ]; then \
        cd "/ComfyUI/custom_nodes/$repo_dir" && \
        python install.py || \
          echo "WARNING: install.py failed for $repo_dir (continuing)"; \
      fi; \
    done < /nodes.lock

# Verify key imports (fail fast if something is broken)
RUN python3 -c "\
import torch; print(f'PyTorch {torch.__version__}'); \
import safetensors; print(f'safetensors {safetensors.__version__}'); \
import transformers; print(f'transformers {transformers.__version__}'); \
import kornia; print('kornia OK'); \
import spandrel; print('spandrel OK'); \
import sageattention; print('sageattention OK'); \
"

# CivitAI downloader (uses aria2c which is already installed above)
RUN git clone --depth 1 https://github.com/Hearmeman24/CivitAI_Downloader /tools/civitai-downloader

# extra_model_paths.yaml tells ComfyUI to look at network volume for models
COPY extra_model_paths.yaml /ComfyUI/extra_model_paths.yaml
COPY log_forwarder.py /log_forwarder.py
COPY start_script.sh /start_script.sh
RUN chmod +x /start_script.sh

CMD ["/start_script.sh"]
