# syntax=docker/dockerfile:1.7
# BuildKit 1.7+ required for `RUN --mount=type=cache` semantics used below.
# Built by CircleCI as `docker buildx build --cache-to=type=registry,mode=max
# --cache-from=type=registry --push`, so every layer is exported to the registry
# (docker.io/hearmeman/comfyui-serverless:buildcache) and re-hydrated across runs.

FROM nvidia/cuda:13.0.3-cudnn-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_PREFER_BINARY=1 \
    CMAKE_BUILD_PARALLEL_LEVEL=8

# System deps. apt caches mounted so successive layer rebuilds reuse the
# .deb downloads; the `rm -rf /var/lib/apt/lists/*` is intentionally dropped
# because that cache is now mount-backed (lives outside the layer).
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    apt-get update && apt-get install -y --no-install-recommends \
    python3.12 python3.12-venv python3.12-dev python3-pip \
    build-essential gcc g++ ninja-build \
    git git-lfs aria2 ffmpeg wget curl ca-certificates \
    libgl1 libglib2.0-0 libopenblas-dev liblapack-dev \
    && ln -sf /usr/bin/python3.12 /usr/bin/python3 \
    && ln -sf /usr/bin/python3.12 /usr/bin/python \
    && python3.12 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

# Pin the torch family to cu130 BEFORE anything else installs torch. The base image
# ships nvcc 13.0, and ComfyUI's requirements.txt lists bare torch/torchvision/torchaudio
# that would otherwise resolve to the default-CUDA wheel. cu130 is REQUIRED for native
# nvfp4 compact loading (cuBLAS 13.x FP4 matmul; on cu128 it returns NOT_SUPPORTED and
# ComfyUI falls back to fp16/fp8). All three pins are the highest mutually-coherent cu130
# cp312 wheels: torchaudio cu130 caps at 2.11.0, so the whole family pins to the 2.11.0
# line (torchvision 0.26.0 pairs with torch 2.11.0). The later `-r requirements.txt`
# then sees the torch family already satisfied and skips it.
RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    pip install --upgrade pip setuptools wheel packaging && \
    pip install torch==2.11.0 torchvision==0.26.0 torchaudio==2.11.0 \
        --index-url https://download.pytorch.org/whl/cu130

# Copy the lockfile that pins every git SHA (ComfyUI core + each custom node).
# Generated by scripts/freeze.py from the local ComfyUI tree. All clones below
# read SHAs from this file — when a SHA bumps the cache miss is exactly at the
# node-loop layer, not earlier (apt / pip / sage / runpod stay hot).
COPY nodes.lock /nodes.lock

# ComfyUI + all deps (includes torch, safetensors, transformers, etc.).
# `--filter=blob:none` skips git history blobs — saves ~30-60s vs full clone
# and works against any github.com SHA (`--depth 1 <sha>` is not universally
# supported). pip cache mount survives across rebuilds of this layer.
RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    pip install --upgrade pip setuptools wheel packaging && \
    COMFY_SHA=$(awk '$1=="https://github.com/comfyanonymous/ComfyUI.git"{print $2}' /nodes.lock) && \
    if [ -z "$COMFY_SHA" ]; then echo "FATAL: ComfyUI SHA missing from nodes.lock" >&2; exit 1; fi && \
    git clone --filter=blob:none https://github.com/comfyanonymous/ComfyUI.git /ComfyUI && \
    git -C /ComfyUI checkout "$COMFY_SHA" && \
    pip install -r /ComfyUI/requirements.txt

# Freeze torch versions to prevent custom node deps from upgrading/downgrading
RUN pip freeze | grep -E "^(torch|torchvision|torchaudio|torchsde)==" > /torch-constraint.txt

# SageAttention — built from source for cu130 (the old cu128 wheel links libcudart.so.12
# and fails to import on cu130). The devel base already provides nvcc 13.0 + cudart-dev +
# cublas-dev, so no extra CUDA apt install is needed. nvcc cross-compiles for the target
# arches without a GPU present (arch is compile-time), so this builds on CPU CI.
#   - SHA d1a57a5 is the proven build point.
#   - TORCH_CUDA_ARCH_LIST uses ';' (setup.py splits on ';'/',', NOT spaces) and EXCLUDES
#     9.0: setup.py broadcasts the full arch list to every module, and the Hopper
#     _qattn_sm90 wgmma kernel cannot assemble for sm_120a. Net coverage: Ampere(8.0) +
#     Ada(8.9) + Blackwell(12.0); no Hopper (sm_90 falls back to default attn, no crash).
#   - --no-build-isolation builds against the already-installed torch 2.11.0+cu130 (build
#     isolation would pull a fresh, possibly-mismatched torch into the build env).
# Import success here is NOT proof the kernel runs — the authoritative check is the
# runtime kernel probe in serverless-runtime/start.sh, which only enables
# --use-sage-attention if a real sageattn launch completes on the actual GPU.
RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    git clone https://github.com/thu-ml/SageAttention.git /tmp/sageattention && \
    git -C /tmp/sageattention checkout d1a57a546c3d395b1ffcbeecc66d81db76f3b4b5 && \
    CUDA_HOME=/usr/local/cuda-13.0 \
    TORCH_CUDA_ARCH_LIST="8.0;8.9;12.0" \
    MAX_JOBS=4 \
    pip install --no-build-isolation /tmp/sageattention && \
    rm -rf /tmp/sageattention

# RunPod SDK + runtime deps
RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    pip install runpod boto3 requests websocket-client

# Clone and install all custom nodes — pinned to SHAs in /nodes.lock.
# Each line is '<url> <sha>'. We skip the ComfyUI core entry (cloned above)
# and clone each node with --filter=blob:none, then `git checkout <sha>`.
# pip cache mount: within a single build of this layer, the 28 pip installs
# share a hot wheel cache (saves ~2-4 min on a clean re-execution).
RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    set -e; \
    while read -r url sha; do \
      case "$url" in ''|'#'*) continue ;; esac; \
      [ "$url" = "https://github.com/comfyanonymous/ComfyUI.git" ] && continue; \
      cd /ComfyUI/custom_nodes; \
      repo_dir=$(basename "$url" .git); \
      echo "=== Installing $repo_dir @ $sha ==="; \
      git clone --filter=blob:none "$url" "$repo_dir"; \
      git -C "$repo_dir" checkout "$sha"; \
      if [ -f "/ComfyUI/custom_nodes/$repo_dir/requirements.txt" ]; then \
        pip install -r "/ComfyUI/custom_nodes/$repo_dir/requirements.txt" \
          --constraint /torch-constraint.txt || \
          echo "WARNING: some deps failed for $repo_dir (continuing)"; \
      fi; \
      if [ -f "/ComfyUI/custom_nodes/$repo_dir/install.py" ]; then \
        cd "/ComfyUI/custom_nodes/$repo_dir" && \
        python install.py || \
          echo "WARNING: install.py failed for $repo_dir (continuing)"; \
      fi; \
    done < /nodes.lock

# Verify key imports (fail fast if something is broken)
RUN python3 -c "\
import torch; print(f'PyTorch {torch.__version__}'); \
import safetensors; print(f'safetensors {safetensors.__version__}'); \
import transformers; print(f'transformers {transformers.__version__}'); \
import kornia; print('kornia OK'); \
import spandrel; print('spandrel OK'); \
import sageattention; print('sageattention OK'); \
"

# CivitAI downloader (uses aria2c which is already installed above).
# SHA-pinned so image content is deterministic and the layer cache only invalidates
# when this ARG is bumped. To update: `git ls-remote https://github.com/Hearmeman24/CivitAI_Downloader HEAD`.
ARG CIVITAI_DL_SHA=2670fc951feb364d91895369530e62b57b90e48d
RUN git clone https://github.com/Hearmeman24/CivitAI_Downloader /tools/civitai-downloader \
 && git -C /tools/civitai-downloader checkout --quiet "$CIVITAI_DL_SHA" \
 && rm -rf /tools/civitai-downloader/.git

# Volatile config + scripts at the END so edits to start_script.sh / yaml
# don't invalidate any heavy layer above. (Ordering matters for cache reuse:
# most-stable first, most-volatile last.)
COPY extra_model_paths.yaml /ComfyUI/extra_model_paths.yaml
COPY log_forwarder.py /log_forwarder.py
COPY start_script.sh /start_script.sh
RUN chmod +x /start_script.sh

CMD ["/start_script.sh"]
