#!/usr/bin/env python3
"""Generate the CircleCI continuation config for the build → deploy → smoke pipeline.

Fetches the live blockflow-presets manifest, builds a YAML config with one
smoke_test job per preset (matrix expanded), and emits to stdout. Called by
the setup job in .circleci/config.yml; output piped to circleci/continuation.

Why generate the matrix here rather than use CircleCI parameter substitution:
matrix.parameters values are evaluated at pipeline-load time. With a dynamic
list pulled from a remote URL, writing the literal list into the YAML is the
cleanest path and lets you see exactly which jobs will run by reading the
generated config.
"""

from __future__ import annotations

import json
import sys
import urllib.request

MANIFEST_URL = "https://raw.githubusercontent.com/Hearmeman24/blockflow-presets/main/manifest.json"
ENDPOINT_ID = "5fkobbksgrtww6"
COMFYGEN_REPO = "https://github.com/Hearmeman24/ComfyGen.git"
COMFYGEN_REF = "main"


def fetch_preset_ids() -> list[str]:
    req = urllib.request.Request(
        MANIFEST_URL,
        headers={"User-Agent": "comfygen-ci/1.0"},
    )
    data = json.loads(urllib.request.urlopen(req, timeout=30).read())
    return [p["id"] for p in data.get("presets", [])]


def yaml_list(items: list[str]) -> str:
    """Render a Python list of strings as a YAML flow-style list."""
    return "[" + ", ".join(f'"{i}"' for i in items) + "]"


def render(preset_ids: list[str]) -> str:
    presets_yaml = yaml_list(preset_ids)
    return f"""\
# Generated by .circleci/generate_continue.py at pipeline setup time.
# Presets at generation time: {presets_yaml}
version: 2.1

executors:
  docker-dind:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: false
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
  python:
    docker:
      - image: cimg/python:3.12

commands:
  notify-flowbot:
    description: Send a webhook notification to FlowBot
    parameters:
      message:
        type: string
    steps:
      - run:
          name: Notify FlowBot
          when: always
          command: |
            if [ -z "$FLOWBOT_WEBHOOK_URL" ] || [ -z "$FLOWBOT_WEBHOOK_TOKEN" ]; then
              echo "Missing webhook env vars, skipping notification."
              exit 0
            fi
            curl -s -X POST "${{FLOWBOT_WEBHOOK_URL}}/hooks/agent" \\
              -H "Authorization: Bearer ${{FLOWBOT_WEBHOOK_TOKEN}}" \\
              -H "Content-Type: application/json" \\
              -d "{{\\"message\\": \\"<< parameters.message >>\\", \\"source\\": \\"circleci\\"}}"

  install-comfygen:
    description: Clone and install ComfyGen CLI from main
    steps:
      - run:
          name: Install comfy-gen from {COMFYGEN_REPO}@{COMFYGEN_REF}
          command: |
            pip install --quiet "git+{COMFYGEN_REPO}@{COMFYGEN_REF}"
            comfy-gen --help >/dev/null

jobs:
  build_and_push:
    executor: docker-dind
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PAT" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Get commit info
          command: |
            echo "export COMMIT_MSG=\\"$(git log -1 --pretty=%s | tr '\"' \"'\" )\\"" >> "$BASH_ENV"
      - notify-flowbot:
          message: "Tell me that the comfyui-serverless:${{CIRCLE_TAG:-latest}} Docker build has started. Commit ${{CIRCLE_SHA1:0:7}}: ${{COMMIT_MSG}}"
      - run:
          name: Build & push ComfyUI serverless image
          command: |
            TAG="${{CIRCLE_TAG:-latest}}"
            IMG="docker.io/$DOCKERHUB_USER/comfyui-serverless"
            docker build --progress=plain -t "${{IMG}}:${{TAG}}" .
            docker push "${{IMG}}:${{TAG}}"
            touch /tmp/build_success
      - run:
          name: Notify FlowBot — build complete
          when: always
          command: |
            TAG="${{CIRCLE_TAG:-latest}}"
            if [ -z "$FLOWBOT_WEBHOOK_URL" ] || [ -z "$FLOWBOT_WEBHOOK_TOKEN" ]; then
              exit 0
            fi
            if [ -f /tmp/build_success ]; then
              MSG="Tell me that the comfyui-serverless:${{TAG}} Docker build succeeded and was pushed to Docker Hub. Commit ${{CIRCLE_SHA1:0:7}}: ${{COMMIT_MSG}}"
            else
              MSG="Tell me that the comfyui-serverless:${{TAG}} Docker build failed. Commit ${{CIRCLE_SHA1:0:7}}: ${{COMMIT_MSG}}. Logs: ${{CIRCLE_BUILD_URL}}"
            fi
            curl -s -X POST "${{FLOWBOT_WEBHOOK_URL}}/hooks/agent" \\
              -H "Authorization: Bearer ${{FLOWBOT_WEBHOOK_TOKEN}}" \\
              -H "Content-Type: application/json" \\
              -d "{{\\"message\\": \\"${{MSG}}\\", \\"source\\": \\"circleci\\"}}"

  update_endpoint:
    executor: python
    steps:
      - run:
          name: PATCH template imageName to new tag
          command: |
            TAG="${{CIRCLE_TAG:-latest}}"
            NEW_IMAGE="hearmeman/comfyui-serverless:${{TAG}}"
            # Fetch the templateId from the endpoint, then patch the template.
            python3 \<<PY
            import json, os, urllib.request
            HDR = {{
                "Authorization": f"Bearer {{os.environ['RUNPOD_API_KEY']}}",
                "Content-Type": "application/json",
                "User-Agent": "comfygen-ci/1.0",
            }}
            ep = json.loads(urllib.request.urlopen(urllib.request.Request(
                "https://rest.runpod.io/v1/endpoints/{ENDPOINT_ID}", headers=HDR
            )).read())
            tid = ep["templateId"]
            print(f"[update_endpoint] endpoint {ENDPOINT_ID} -> templateId {{tid}}, current version {{ep.get('version')}}")
            body = json.dumps({{"imageName": "${{NEW_IMAGE}}"}}).encode()
            req = urllib.request.Request(
                f"https://rest.runpod.io/v1/templates/{{tid}}",
                data=body, headers=HDR, method="PATCH",
            )
            resp = json.loads(urllib.request.urlopen(req).read())
            print(f"[update_endpoint] PATCHed template {{tid}} -> imageName={{resp.get('imageName')}}")
            PY

  wait_for_rollout:
    executor: python
    steps:
      - checkout
      - install-comfygen
      - run:
          name: Wait for all endpoint pods to be on new image tag
          no_output_timeout: 30m
          command: |
            TAG="${{CIRCLE_TAG:-latest}}"
            # Fetch the wait_for_rollout script from the handler repo.
            curl -sSL "https://raw.githubusercontent.com/Hearmeman24/ComfyGen/main/automation/wait_for_rollout.py" -o /tmp/wait_for_rollout.py
            python3 /tmp/wait_for_rollout.py --endpoint-id {ENDPOINT_ID} --image-tag "${{TAG}}" --timeout 1800 --interval 30

  smoke_test:
    parameters:
      preset_id:
        type: string
    executor: python
    steps:
      - checkout
      - install-comfygen
      - run:
          name: Configure comfy-gen
          command: |
            mkdir -p ~/.config/comfy-gen
            comfy-gen config --set runpod_api_key="${{RUNPOD_API_KEY}}"
            comfy-gen config --set endpoint_id="{ENDPOINT_ID}"
            comfy-gen config --set civitai_token="${{CIVITAI_TOKEN}}" || true
      - run:
          name: Run smoke for preset << parameters.preset_id >>
          no_output_timeout: 60m
          command: |
            curl -sSL "https://raw.githubusercontent.com/Hearmeman24/ComfyGen/main/automation/smoke_preset.py" -o /tmp/smoke_preset.py
            python3 /tmp/smoke_preset.py "<< parameters.preset_id >>" --endpoint-id {ENDPOINT_ID} --workflow-timeout 2700

  notify_done:
    executor: python
    steps:
      - notify-flowbot:
          message: "Tell me that the comfyui-serverless:${{CIRCLE_TAG:-latest}} full pipeline (build + rollout + smoke) succeeded. Commit ${{CIRCLE_SHA1:0:7}}."

workflows:
  build-deploy-smoke:
    jobs:
      - build_and_push:
          context: [docker-hub, flowbot-webhook-token]
      - update_endpoint:
          context: [docker-hub]
          requires: [build_and_push]
      - wait_for_rollout:
          context: [docker-hub]
          requires: [update_endpoint]
      - smoke_test:
          context: [docker-hub]
          requires: [wait_for_rollout]
          matrix:
            parameters:
              preset_id: {presets_yaml}
      - notify_done:
          context: [flowbot-webhook-token]
          requires: [smoke_test]
"""


def main() -> None:
    preset_ids = fetch_preset_ids()
    if not preset_ids:
        print("ERROR: no presets in manifest", file=sys.stderr)
        sys.exit(1)
    print(f"[generate_continue] presets: {preset_ids}", file=sys.stderr)
    sys.stdout.write(render(preset_ids))


if __name__ == "__main__":
    main()
